# clusters/my-cluster/infra/loki-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      # Artifact Hub 또는 GitHub에서 확인한 안정적인 최신 버전
      version: "6.30.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Helm 차트의 공식 values.yaml 구조에 맞춘 최종 설정
  values:
    # 1. 실행 모드를 'SingleBinary'로 최상단에 명시합니다.
    #    이렇게 하면 'scalable targets' 유효성 검사 오류가 해결됩니다.
    deploymentMode: SingleBinary
    
    # 2. 'loki:' 키 아래에, 필요한 설정만 개별적으로 덮어씁니다.
    #    이것이 Helm 템플릿 오류를 해결하는 가장 확실한 방법입니다.
    loki:
      # 2-1. 저장소 타입을 'filesystem'으로 명시합니다.
      #      이 설정은 차트가 S3 같은 오브젝트 스토리지 설정을 찾지 않도록 합니다.
      storage:
        type: 'filesystem'
      
      # 2-2. 스키마 설정을 최신 TSDB 방식으로 덮어씁니다.
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
            
    # 3. 'singleBinary:' 모드에 대한 세부 설정을 정의합니다.
    singleBinary:
      replicas: 1
      # 영속성을 위한 디스크 설정
      persistence:
        enabled: true
        size: 10Gi
      # Pod에 대한 자원 제한 설정
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: "1" # 1 core
          memory: 1Gi
    
    # 4. 테스트 기능은 비활성화하여 용량 초과 오류를 방지합니다.
    test:
      enabled: false

    # 5. 분산 모드 컴포넌트들은 사용하지 않으므로 명시적으로 비활성화합니다.
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
