apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/infra # 'infra' 폴더를 가리킴
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system