name: Build and Push Docker Images

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 실행

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Buildx 설정 (멀티-플랫폼 빌드 등 지원)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. GitHub Container Registry (GHCR)에 로그인
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 프론트엔드 이미지 빌드 및 푸시 ---
      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
          # 빌드 캐시를 사용하여 후속 빌드 속도 향상
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- 백엔드 이미지 빌드 및 푸시 ---
      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
          # 빌드 캐시를 사용하여 후속 빌드 속도 향상
          cache-from: type=gha
          cache-to: type=gha,mode=max